statsbomb_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres # <— le nom du service Postgres dans docker-compose
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 4
